application:
  name: "restapi"
  project: "api"
  organization: "QoveryCommunity"
  publicly_accessible: true
  storage:
  - name: "asset"
    size: "2000"
    type: "hdd"
    mount_point: "/mnt/asset"
databases:
- type: "MONGODB"
  name: "ct"
  version: "4.4"
routers:
- name: main
  routes:
  - application_name: simple-example-node-with-postgresql
    paths:
    - /
