---
application:
  name: "restapi"
  project: "test"
  organization: "QoveryCommunity"
  storage:
  - name: "test"
    size: "200"
    type: "fast_ssd"
    mount_point: "/mnt/test"
databases:
- type: "MONGODB"
  name: "test"
  version: "4.4"
routers:
- name: "main-restapi"
  routes:
  - application_name: "restapi"
    paths:
    - "/*"
